import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppLayout from "./appLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" className={inter.className}>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
